[package]
publish = false
name = "minify-html-ruby"
version = "0.6.10"
authors = ["Wilson Lin <code@wilsonl.in>"]
edition = "2018"

[lib]
name = "minify_html_ruby_lib"
crate-type = ["cdylib"]

[dependencies]
minify-html = { path = "../rust/main", features = ["js-esbuild"] }
rutie = "0.7.0"
