[package]
publish = false
name = "minify-html-java"
version = "0.4.3"
authors = ["Wilson Lin <code@wilsonl.in>"]
edition = "2018"

[dependencies]
minify-html = { path = "..", features = ["js-esbuild"] }
jni = "0.14.0"

[lib]
crate-type = ["cdylib"]
path = "src/main/rust/lib.rs"
