[package]
publish = false
name = "minify_html_core"
description = "Extremely fast and smart HTML minifier"
license = "MIT"
homepage = "https://github.com/wilsonzlin/minify-html"
readme = "README.md"
repository = "https://github.com/wilsonzlin/minify-html.git"
version = "0.5.2"
authors = ["Wilson Lin <code@wilsonl.in>"]
edition = "2018"

[lib]
name = "minify_html_core"
crate-type = ["cdylib"]

[dependencies]
minify-html = { path = "..", features = [] }
[dependencies.pyo3]
version = "0.13.0"
features = ["extension-module"]
